### ISSUE TITLE
Can no longer contact advertisor?

### ISSUE THREAD

**Issue by a1diablo** [AnthonyBloomer/daftlistings#139]
This method seems to be removed from the new version. I did a bit of digging and found that sending an enquiry is guarded by a recaptcha for an unauthenticated user. Do we have a workaround for this?

**Comment by sdfordham** [comment]
The auth endpoint is listed [here](https://auth.daft.ie/auth/realms/daft/). But I cannot see how to login via POST without a fingerprint, maybe someone else can.

So otherwise, you might think of using e.g. [Selenium](https://selenium-python.readthedocs.io/) to do login and get the bearer token/cookie, but actually this package is not compatible with that approach because you can't edit the request header (it is hard-coded into the `Daft` class) and you cant pass a cookie because we don't use a [`Session` object](https://docs.python-requests.org/en/master/user/advanced/#session-objects) or even expose the request object. So with either approach, a PR is needed here if you want to use this package as far as I can see.

**Comment by sdfordham** [comment]
I'm going to close this for now, if anyone wants to make a PR adding this functionality then fire ahead.
