### ISSUE TITLE
Update property-for-sale

### ISSUE THREAD

**Issue by ahanway** [AnthonyBloomer/daftlistings#45]
The scaper no longer works for property-for-sale urls due to the page theme changing. The scraper currently searches using `soup.find_all("div", {"class": "box"})`, this needs to be updated to `soup.find_all("div", {"class": "PropertyCardContainer__container"})` and the listings object subsequently parsing that string needs to be updated.

**Comment by AnthonyBloomer** [comment]
Hi @ahanway, thanks for raising this issue. I did notice it earlier in the week. I plan to start work on this soon. Any PR would be welcome on this as there is a lot to rewrite. I've created a branch `daft-new-theme`.

**Comment by AnthonyBloomer** [comment]
Update regrading this, Daft is moving their frontend to React so I'm going to hold of updating this library until they fully migrate.

**Comment by ahanway** [comment]
Does this mean the html is going to be completely different?

**Comment by AnthonyBloomer** [comment]
Hey @ahanway, from looking into this, all of the CSS selectors are different on the search results and listing page for properties for sale now.

**Comment by ShashiSingam** [comment]
Hey Anthony,

Thank you very much for this work, I really appreciate it very much.

However I have the bug still "SaleType" for new properties. This is my first time I am doing the "web scrapping". May be I missed something from your explanation. Could you please let me know how to get  house prices for sale. 
Thank you,
Shashi

**Comment by AnthonyBloomer** [comment]
Hi Shashi,

Clone the repo and checkout the `daft-property-for-sale` branch. On this branch, you can get name, address, description and price of the property listing.

```
git clone https://github.com/AnthonyBloomer/daftlistings.git
git checkout daft-property-for-sale
```

**Comment by jacobmcelwee** [comment]
Hi Anthony, 
I'm trying to create a CSV file with price, property, description, numRooms, location. Any chance you will ever release a Dataset with this tool. 

Thanks

**Comment by AnthonyBloomer** [comment]
@jacobmcelwee, that's a good idea. You could use something like this to create your own dataset:

```python
from daftlistings import Daft, RentType, SortOrder, SortType
import csv

daft = Daft()

daft.set_county('Dublin')
daft.set_listing_type(RentType.APARTMENTS)
daft.set_sort_order(SortOrder.ASCENDING)
daft.set_sort_by(SortType.PRICE)
daft.set_with_photos(True)
daft.set_open_viewing(True)

listings = daft.search()

with open('data.csv', "w") as f:
    writer = csv.writer(f)
    for listing in listings:
        writer.writerow([listing.price, listing.dwelling_type, listing.bedrooms, listing.formalised_address])
```

**Comment by AnthonyBloomer** [comment]
I would like to provide an update on this issue. I have been thinking of a strategy to resolving it as well as making this library a lot more maintainable if any changes are introduced on Daft's side in the future.

Initially how the parsing of HTML elements worked is that in the Daft search method, I would find all selectors called `box`. A `box` div element contains things such as the property address, price, and photo. For each of those elements, the HTML would be passed to the Listing class. The Listing class properties finds and return the HTML or CSS selector. The search method then returns an array of Listing objects.  

Since there is currently differences between the HTML and CSS on daft.ie pages for rental and sale properties, A while back I did add a `PropertyForRent` and `PropertyForSale` class. The reasoning behind this is rather than adding more code to each method within the `Listing` class to fix the issues introduced, this does keep things cleaner and will hopefully result in making this library a lot more easier to maintain in the future. 

So what I have so far is I updated the search method to check if we can't find the div class selector `box` that is currently used for rental properties then the method will return a list of PropertyForSale objects:

``` python
divs = soup.find_all("div", {"class": "box"})
if len(divs) == 0:
    divs = soup.find_all("div", {"class": "PropertyCardContainer__container"})
    [listings.append(PropertyForSale(div, self._debug)) for div in divs]
else:
    [listings.append(PropertyForRent(div, self._debug)) for div in divs]
```

A while back we did add some checks within the Listing class such as if we can't find a selector that is used on the properties for rent UI then it will try to find a selector used on the properties for sale UI. This will be removed from there and any logic of parsing the HTML will be moved to its respective class i.e. `PropertyForSale`.

So the next steps here would be to go through each method in the `Listing` class to check if there's any differences betwen the html for properties for rent and properties for sale on Daft.ie. If there is then the logic will be seperated to their respective class. Methods that aren't affected will remain in the `Listing` class. 

I also think it would be good to split the tests into seperate files (i.e. test_property_for_rent, test_property_for_sale) so it'll be easier to quickly spot any issues and improve the stability and maintainability of the project. I have created a seperate issue for that here: https://github.com/AnthonyBloomer/daftlistings/issues/66

If you have any thoughts on this approach / would like to get involved please let me know!

**Comment by AnthonyBloomer** [comment]
[v1.8.0](https://pypi.org/project/daftlistings/1.8.0/) has been released which addresses the points made above.
